import Head from "next/head";
import Coach from "./CoachPage/Coach";

import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Loader from "../shared/ui/Loader";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [inToken, setInToken] = useState(false);
  const router = useRouter();
  const { token } = router.query;

  setTimeout(() => {
    setInToken(true);
  }, [300]);

  useEffect(() => {
    function start() {
      if (inToken) {
        if (token) {
          localStorage.setItem("token", token);
          router.push(`/?token=${token}`);
        } else {
          const localToken = localStorage.getItem("token");
          if (localToken) {
            router.push(`/?token=${localToken}`);
          }
        }
        setLoading(false);
      }
    }
    start();
  }, [inToken]);

  if (loading) {
    return <Loader />;
  }

  return (
    <>
      <Head>
        <title>AF CLUB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Coach />
    </>
  );
}
